-- ============================================================
-- مدرسة القمم النجاح - مخطط قاعدة بيانات PostgreSQL
-- مطابق تماماً لمخطط SQLite (server/db/schema.sql)
-- ============================================================

-- المستخدمون (يوحّد الطلاب والإدارة لأغراض المصادقة)
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('ROLE_STUDENT', 'ROLE_ADMIN')),
  active        INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- السنة الدراسية
CREATE TABLE IF NOT EXISTS academic_years (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      TEXT NOT NULL UNIQUE,
  is_active INTEGER NOT NULL DEFAULT 1
);

-- المستويات
CREATE TABLE IF NOT EXISTS levels (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL
);

-- الشعب (مرتبطة بمستوى)
CREATE TABLE IF NOT EXISTS classes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level_id   BIGINT NOT NULL REFERENCES levels(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE(level_id, name)
);

-- المواد
CREATE TABLE IF NOT EXISTS subjects (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- التلاميذ
CREATE TABLE IF NOT EXISTS students (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  first_name       TEXT NOT NULL,
  last_name        TEXT NOT NULL,
  reg_number       TEXT NOT NULL UNIQUE,
  phone            TEXT,
  level_id         BIGINT NOT NULL REFERENCES levels(id),
  class_id         BIGINT REFERENCES classes(id),
  academic_year_id BIGINT REFERENCES academic_years(id),
  status           INTEGER NOT NULL DEFAULT 1,
  created_at       TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- الأساتذة
CREATE TABLE IF NOT EXISTS teachers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL,
  subject_id BIGINT NOT NULL REFERENCES subjects(id),
  photo      TEXT,
  status     INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- المستويات التي يدرسها الأستاذ
CREATE TABLE IF NOT EXISTS teacher_levels (
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  level_id   BIGINT NOT NULL REFERENCES levels(id) ON DELETE CASCADE,
  PRIMARY KEY (teacher_id, level_id)
);

-- الشعب التي يدرسها الأستاذ
CREATE TABLE IF NOT EXISTS teacher_classes (
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  class_id   BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  PRIMARY KEY (teacher_id, class_id)
);

-- الأفواج
CREATE TABLE IF NOT EXISTS groups (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES subjects(id),
  level_id   BIGINT NOT NULL REFERENCES levels(id),
  class_id   BIGINT REFERENCES classes(id),
  name       TEXT NOT NULL,
  day        TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time   TEXT NOT NULL,
  capacity   INTEGER NOT NULL CHECK (capacity > 0),
  status     INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- اختيارات التلاميذ للأفواج
-- قيد UNIQUE(student_id, teacher_id) يمنع اختيار أكثر من فوج لنفس الأستاذ
CREATE TABLE IF NOT EXISTS student_group_selections (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  group_id   BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  status     TEXT NOT NULL DEFAULT 'confirmed',
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (student_id, teacher_id)
);

CREATE INDEX IF NOT EXISTS idx_selections_group ON student_group_selections(group_id);
CREATE INDEX IF NOT EXISTS idx_selections_student ON student_group_selections(student_id);

-- الدفعات الشهرية (0=سبتمبر ... 8=ماي)
CREATE TABLE IF NOT EXISTS payments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  month_index  INTEGER NOT NULL CHECK (month_index BETWEEN 0 AND 8),
  payment_date TEXT,
  is_paid      INTEGER NOT NULL DEFAULT 0,
  note         TEXT,
  created_by   BIGINT REFERENCES users(id),
  updated_at   TEXT,
  UNIQUE (student_id, month_index)
);

-- الجدول الدراسي (يعكس بيانات الأفواج)
CREATE TABLE IF NOT EXISTS schedules (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id   BIGINT NOT NULL UNIQUE REFERENCES groups(id) ON DELETE CASCADE,
  day        TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time   TEXT NOT NULL
);

-- الإعلانات
CREATE TABLE IF NOT EXISTS announcements (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message    TEXT NOT NULL DEFAULT '',
  images     TEXT NOT NULL DEFAULT '[]',
  status     INTEGER NOT NULL DEFAULT 1,
created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT
);

-- Payment cycles: one row per monthly billing cycle (day 12 -> day 11)
-- No fixed anchor date: any month produces its own cycle.
-- anchor_date = start_date of the cycle itself and cycle_index = absolute month ordinal (year*12 + month - 1)
CREATE TABLE IF NOT EXISTS payment_cycles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anchor_date TEXT NOT NULL,
  start_date  TEXT NOT NULL UNIQUE,
  end_date    TEXT NOT NULL,
  label       TEXT NOT NULL,
  cycle_index INTEGER NOT NULL,
  created_at  TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_payment_cycles_end ON payment_cycles (end_date);
CREATE INDEX IF NOT EXISTS idx_payment_cycles_idx ON payment_cycles (cycle_index);

-- Payment records linked to a cycle instead of a fixed month_index
CREATE TABLE IF NOT EXISTS cycle_payments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  cycle_id   BIGINT NOT NULL REFERENCES payment_cycles(id) ON DELETE CASCADE,
  status     TEXT NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PAID')),
  amount     NUMERIC,
  paid_at    TEXT,
  created_by BIGINT REFERENCES users(id),
  note       TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT,
  UNIQUE (student_id, cycle_id)
);

CREATE INDEX IF NOT EXISTS idx_cycle_payments_cycle ON cycle_payments (cycle_id);
CREATE INDEX IF NOT EXISTS idx_cycle_payments_student ON cycle_payments (student_id);
CREATE INDEX IF NOT EXISTS idx_cycle_payments_status ON cycle_payments (cycle_id, status);

-- Audit trail: keeps the full history even when a payment row is cancelled/edited
CREATE TABLE IF NOT EXISTS payment_audit (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_payments_id BIGINT,
  cycle_id          BIGINT,
  student_id        BIGINT NOT NULL,
  action            TEXT NOT NULL,
  from_status       TEXT,
  to_status         TEXT,
  amount            NUMERIC,
  user_id           BIGINT REFERENCES users(id),
  created_at        TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_payment_audit_student ON payment_audit (student_id);
CREATE INDEX IF NOT EXISTS idx_payment_audit_cycle ON payment_audit (cycle_id);

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1)) WHERE EXISTS (SELECT 1 FROM users);
SELECT setval(pg_get_serial_sequence('payment_cycles', 'id'), COALESCE((SELECT MAX(id) FROM payment_cycles), 1)) WHERE EXISTS (SELECT 1 FROM payment_cycles);
SELECT setval(pg_get_serial_sequence('cycle_payments', 'id'), COALESCE((SELECT MAX(id) FROM cycle_payments), 1)) WHERE EXISTS (SELECT 1 FROM cycle_payments);